export * from "./kategori"
export * from "./program"
export * from "./artikel"
export * from "./banksoal"
export * from "./faq"
export * from "./testimoni"
export * from "./galeri"
export * from "./settings"
